import type { DiscoveredComponentManifest } from "./catalog-discovery.ts";
import { componentSourceId } from "./catalog-render-definitions.ts";
import { renderTsValue } from "./ts-literal-renderer.ts";

const generatedHeader =
  "// Generated by scripts/generate-catalog.ts. Do not edit by hand.\n";

export function createSourceManifest({
  discovered,
  componentHashes,
  manifestHash,
  filesHash,
  packageVersion,
}: {
  discovered: readonly DiscoveredComponentManifest[];
  componentHashes: ReadonlyMap<string, string>;
  manifestHash: string;
  filesHash: string;
  packageVersion: string;
}) {
  const groups = [...new Set(discovered.map((component) => component.group))].sort();
  const componentSummaries = discovered.map((component) => ({
    id: component.manifest.id,
    displayName: component.manifest.displayName,
    group: component.manifest.group,
    ...(component.manifest.section ? { section: component.manifest.section } : {}),
    source: "static",
    sourceId: componentSourceId,
    version: component.manifest.version,
    renderable: component.manifest.renderable,
    tags: component.manifest.tags,
    sourcePath: component.packagePath,
    contentHash: componentHashes.get(component.manifest.id)!,
    ...(component.manifest.responsiveDefaults
      ? { responsiveDefaults: component.manifest.responsiveDefaults }
      : {}),
    ...(component.manifest.fixtureVariants
      ? { fixtureVariants: component.manifest.fixtureVariants }
      : {}),
    ...(component.manifest.stateSupport ? { stateSupport: component.manifest.stateSupport } : {}),
  }));
  const groupSummaries = groups.map((group) => ({
    id: group,
    displayName: toTitleCase(group),
    componentIds: discovered
      .filter((component) => component.group === group)
      .map((component) => component.manifest.id),
  }));

  return {
    schemaVersion: 1,
    sourceId: componentSourceId,
    name: "Newsnight Components",
    version: packageVersion,
    generatedAt: "1970-01-01T00:00:00.000Z",
    packageName: "@flow-builder/newsnight-components",
    components: componentSummaries,
    groups: groupSummaries,
    fingerprints: {
      manifestHash,
      filesHash,
    },
  };
}

export function renderSourceManifestJson(sourceManifest: ReturnType<typeof createSourceManifest>) {
  return `${JSON.stringify(sourceManifest, null, 2)}\n`;
}

export function renderSourceManifestSource(sourceManifest: ReturnType<typeof createSourceManifest>) {
  return `${generatedHeader}import type { ComponentSourceManifest } from "../sdk/public-sdk";

export const staticComponentSourceManifest = ${renderTsValue(sourceManifest)} satisfies ComponentSourceManifest;
`;
}

function toTitleCase(value: string) {
  return value
    .split("-")
    .map((segment) => `${segment.slice(0, 1).toUpperCase()}${segment.slice(1)}`)
    .join(" ");
}
