import type { DiscoveredComponentManifest } from "./catalog-discovery.ts";
import {
  collectComponentSourceFiles,
  collectSharedDependencySourceFilePaths,
  collectSharedSourceFiles,
} from "./catalog-source-snapshot.ts";
import { renderTsValue } from "./ts-literal-renderer.ts";

const generatedHeader =
  "// Generated by scripts/generate-catalog.ts. Do not edit by hand.\n";

export function renderSourceFilesSource({
  discovered,
  packageRoot,
}: {
  discovered: readonly DiscoveredComponentManifest[];
  packageRoot: string;
}) {
  const componentFilesById = Object.fromEntries(
    discovered.map((component) => [component.manifest.id, collectComponentSourceFiles(component)]),
  );
  const sharedFiles = collectSharedSourceFiles(packageRoot);
  const sharedFilePathsByComponentId = Object.fromEntries(
    discovered.map((component) => [
      component.manifest.id,
      collectSharedDependencySourceFilePaths(component, packageRoot),
    ]),
  );

  return `${generatedHeader}export type ComponentSourceFileMap = Readonly<Record<string, string>>;

export const staticComponentSharedSourceFiles: ComponentSourceFileMap = ${renderTsValue(sharedFiles)};

export const staticComponentSharedSourceFilePathsByComponentId: Readonly<Record<string, readonly string[]>> = ${renderTsValue(sharedFilePathsByComponentId)};

export const staticComponentSourceFilesByComponentId: Readonly<Record<string, ComponentSourceFileMap>> = ${renderTsValue(componentFilesById)};

export function getBuiltInComponentSourceFiles(componentId: string): ComponentSourceFileMap | undefined {
  const componentFiles = staticComponentSourceFilesByComponentId[componentId];
  if (!componentFiles) return undefined;
  const sharedFiles = Object.fromEntries(
    (staticComponentSharedSourceFilePathsByComponentId[componentId] ?? []).map((filePath) => [
      filePath,
      staticComponentSharedSourceFiles[filePath]!,
    ]),
  );

  return {
    ...componentFiles,
    ...sharedFiles,
  };
}
`;
}
