import type { DiscoveredComponentManifest } from "./catalog-discovery.ts";

const generatedHeader =
  "// Generated by scripts/generate-catalog.ts. Do not edit by hand.\n";

export const componentSourceId = "flow-components-test";

export function renderCatalogSource(discovered: readonly DiscoveredComponentManifest[]) {
  const importLines = discovered.map(
    (component) =>
      `import { componentDefinition as ${definitionIdentifier(component)} } from "../groups/${component.group}/${component.folderName}/component";`,
  );
  const groups = [...new Set(discovered.map((component) => component.group))].sort();
  const definitionEntries = discovered.map((component) => `  ${definitionIdentifier(component)},`);
  const catalogEntries = discovered.map(
    (component) => `    {
      id: ${JSON.stringify(component.manifest.id)},
      group: ${JSON.stringify(component.manifest.group)},
      title: ${JSON.stringify(component.manifest.displayName)},
      description: ${definitionIdentifier(component)}.description,
      source: "static",
      sourceId: ${JSON.stringify(componentSourceId)},
    },`,
  );

  return `${generatedHeader}${importLines.join("\n")}
import type {
  ComponentDefinition,
  ComponentGroupId,
  ComponentPackageCatalog,
} from "../sdk/public-sdk";

type AnyComponentDefinition = ComponentDefinition<any>;

export const staticComponentDefinitions = [
${definitionEntries.join("\n")}
] as const satisfies readonly AnyComponentDefinition[];

const staticComponentGroups = [
${groups.map((group) => `  ${JSON.stringify(group)},`).join("\n")}
] as const satisfies readonly ComponentGroupId[];

export const staticComponentPackageCatalog = {
  groups: staticComponentGroups,
  components: [
${catalogEntries.join("\n")}
  ],
  definitions: staticComponentDefinitions as readonly AnyComponentDefinition[],
} satisfies ComponentPackageCatalog;

export const staticComponentPackageDefinitionIds: readonly string[] =
  staticComponentDefinitions.map((definition) => definition.id);

export function getBuiltInComponentDefinition(
  componentId: string,
): AnyComponentDefinition | undefined {
  return staticComponentDefinitions.find((definition) => definition.id === componentId);
}

export function requireBuiltInComponentDefinition(componentId: string): AnyComponentDefinition {
  const definition = getBuiltInComponentDefinition(componentId);
  if (!definition) {
    throw new Error(\`Unknown built-in component definition "\${componentId}".\`);
  }
  return definition;
}
`;
}

function definitionIdentifier(component: DiscoveredComponentManifest) {
  return `${component.manifest.id.replace(/[^a-zA-Z0-9]+/g, "_")}Definition`;
}
